const API="https://anmol-fashion.onrender.com";let KEY=sessionStorage.getItem("af_admin_key")||"",orders=[];const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0});
const dt=s=>s?new Date(s).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const st=s=>String(s||"placed").replaceAll("_"," ");
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json","x-admin-key":KEY,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function login(){KEY=$("key").value.trim();if(!KEY)return $("loginMsg").textContent="Enter admin key.";try{await api("/api/admin/orders?limit=1");sessionStorage.setItem("af_admin_key",KEY);$("login").classList.add("hidden");$("crm").classList.remove("hidden");load()}catch(e){KEY="";$("loginMsg").textContent="Invalid admin key or API connection."}}
$("loginBtn").onclick=login;$("key").onkeydown=e=>e.key==="Enter"&&login();$("logout").onclick=()=>{sessionStorage.removeItem("af_admin_key");location.reload()};
document.querySelectorAll(".nav,.link").forEach(b=>b.onclick=()=>page(b.dataset.page));function page(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(p).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("title").textContent=p[0].toUpperCase()+p.slice(1);if(p==="orders")renderOrders();if(p==="customers")renderCustomers()}
$("refresh").onclick=load;
async function load(){try{let d=await api("/api/admin/orders?limit=500");orders=d.orders||[];renderDashboard();renderOrders();renderCustomers()}catch(e){$("recent").innerHTML=`<tr><td colspan="6">Unable to load orders.</td></tr>`}}
function renderDashboard(){let sales=orders.reduce((a,o)=>a+Number(o.total||0),0),pending=orders.filter(o=>!["delivered","cancelled"].includes(o.status)).length,del=orders.filter(o=>o.status==="delivered").length;$("ordersCount").textContent=orders.length;$("sales").textContent=money(sales);$("pending").textContent=pending;$("delivered").textContent=del;$("recent").innerHTML=orders.slice(0,8).map(o=>row(o,true)).join("")||`<tr><td colspan="6">No orders yet.</td></tr>`}
function row(o,recent=false){return `<tr><td><b class="id">${esc(o.order_id)}</b><span class="sub">${esc(o.payment_method||"COD")}</span></td><td><b>${esc(o.customer_name)}</b><span class="sub">${esc(o.mobile)}</span></td>${recent?`<td><b>${money(o.total)}</b></td>`:`<td>${Array.isArray(o.items)?o.items.reduce((a,i)=>a+Number(i.qty||1),0):"—"}</td><td><b>${money(o.total)}</b></td>`}<td><span class="badge ${esc(o.status)}">${esc(st(o.status))}</span></td><td>${dt(o.created_at)}</td><td><button class="action" onclick="manage('${esc(o.order_id)}')">${recent?"View":"Manage"}</button></td></tr>`}
function renderOrders(list=orders){$("orderRows").innerHTML=list.map(o=>row(o,false)).join("")||`<tr><td colspan="7">No orders found.</td></tr>`}
$("search").oninput=e=>{let q=e.target.value.toLowerCase();renderOrders(orders.filter(o=>[o.order_id,o.customer_name,o.mobile,o.city].some(v=>String(v||"").toLowerCase().includes(q))))}
function renderCustomers(){let m={};orders.forEach(o=>{let k=o.mobile||o.customer_name||"unknown";if(!m[k])m[k]={name:o.customer_name||"Customer",mobile:o.mobile||"",orders:0,total:0};m[k].orders++;m[k].total+=Number(o.total||0)});$("customerGrid").innerHTML=Object.values(m).sort((a,b)=>b.orders-a.orders).map(c=>`<article class="customer"><div class="avatar">${esc((c.name[0]||"A").toUpperCase())}</div><h4>${esc(c.name)}</h4><p>${esc(c.mobile)}</p><b>${c.orders} order(s) · ${money(c.total)}</b></article>`).join("")||"<p>No customers yet.</p>"}
window.manage=function(id){let o=orders.find(x=>x.order_id===id);if(!o)return;let items=Array.isArray(o.items)?o.items:[];$("modalBody").innerHTML=`<div class="kicker">ORDER MANAGEMENT</div><h2>${esc(o.order_id)}</h2><p class="sub">${dt(o.created_at)}</p><div class="detail-grid"><div class="detail"><label>Customer</label><b>${esc(o.customer_name)} · ${esc(o.mobile)}</b></div><div class="detail"><label>Total</label><b>${money(o.total)} · ${esc(o.payment_method||"COD")}</b></div><div class="detail"><label>Address</label><b>${esc([o.address,o.city,o.pincode].filter(Boolean).join(", "))}</b></div><div class="detail"><label>Products</label><b>${items.length} line item(s)</b></div></div><div class="formgrid"><div class="field"><label>Status</label><select id="s">${["placed","confirmed","packed","shipped","out_for_delivery","delivered","cancelled"].map(x=>`<option value="${x}" ${o.status===x?"selected":""}>${st(x)}</option>`).join("")}</select></div><div class="field"><label>Courier</label><input id="c" value="${esc(o.courier_name||"")}" placeholder="Courier name"></div><div class="field"><label>Tracking Number</label><input id="t" value="${esc(o.tracking_number||"")}" placeholder="Tracking number"></div><div class="field"><label>Expected Delivery</label><input id="d" type="date" value="${esc(o.expected_delivery||"")}"></div></div><button class="save" id="save">Save Order Update</button><p id="msg"></p>`;$("modal").classList.remove("hidden");$("save").onclick=()=>save(id)}
async function save(id){$("save").disabled=true;try{let d=await api("/api/admin/orders/"+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({status:$("s").value,courier_name:$("c").value.trim(),tracking_number:$("t").value.trim(),expected_delivery:$("d").value||null})});let i=orders.findIndex(x=>x.order_id===id);if(i>=0)orders[i]=d.order;$("msg").textContent="Saved successfully.";setTimeout(()=>{$("modal").classList.add("hidden");renderDashboard();renderOrders();renderCustomers()},500)}catch(e){$("msg").textContent=e.message;$("save").disabled=false}}
$("close").onclick=()=>$("modal").classList.add("hidden");$("modal").onclick=e=>e.target===$("modal")&&$("modal").classList.add("hidden");
if(KEY){$("key").value=KEY;login()}
