create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  customer_name text not null,
  mobile text not null,
  address text not null,
  city text not null,
  pincode text not null,
  payment_method text not null,
  items jsonb not null,
  total numeric(12,2) not null,
  status text not null default 'placed',
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
-- The backend uses the service-role key, so public users do not need direct table access.
