const API_BASE='https://anmol-fashion.onrender.com';
const products=[
{id:'AF-M-001',name:"Men's Casual Shirt",category:'Men',price:499,oldPrice:799,tag:'Best Seller',sizes:['S','M','L','XL'],colors:['Black','White','Olive'],image:'https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=800&q=85'},
{id:'AF-W-001',name:"Women's Premium Kurti",category:'Women',price:599,oldPrice:999,tag:'New',sizes:['S','M','L','XL'],colors:['Black','Beige','Rose'],image:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=85'},
{id:'AF-M-002',name:'Classic Denim Jeans',category:'Men',price:799,oldPrice:1299,tag:'Trending',sizes:['30','32','34','36'],colors:['Blue','Black'],image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=85'},
{id:'AF-W-002',name:'Minimal Everyday Top',category:'Women',price:499,oldPrice:799,tag:'Bestseller',sizes:['S','M','L'],colors:['White','Black','Cream'],image:'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=800&q=85'},
{id:'AF-K-001',name:'Kids Comfort T-Shirt',category:'Kids',price:399,oldPrice:599,tag:'Popular',sizes:['2Y','4Y','6Y','8Y'],colors:['Blue','White','Yellow'],image:'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=85'},
{id:'AF-K-002',name:'Kids Party Dress',category:'Kids',price:599,oldPrice:899,tag:'New',sizes:['2Y','4Y','6Y','8Y'],colors:['Pink','Cream'],image:'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=85'},
{id:'AF-M-003',name:'Premium Polo Tee',category:'Men',price:549,oldPrice:899,tag:'New',sizes:['S','M','L','XL'],colors:['Navy','White'],image:'https://images.unsplash.com/photo-1625910513413-5fc45a5f6c5d?auto=format&fit=crop&w=800&q=85'},
{id:'AF-W-003',name:'Elegant Co-ord Set',category:'Women',price:899,oldPrice:1499,tag:'New',sizes:['S','M','L'],colors:['Black','Sand'],image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=85'}];
let cart=JSON.parse(localStorage.getItem('anmol_cart')||'[]'),wishlist=JSON.parse(localStorage.getItem('anmol_wishlist')||'[]'),cat='All',query='',selected=null,size=null,color=null;
const $=x=>document.getElementById(x),money=n=>'₹'+Number(n).toLocaleString('en-IN');
function save(){localStorage.setItem('anmol_cart',JSON.stringify(cart));localStorage.setItem('anmol_wishlist',JSON.stringify(wishlist));counts()}
function counts(){$('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);$('wishCount').textContent=wishlist.length}
function list(){let a=products.filter(p=>(cat==='All'||p.category===cat)&&`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));let s=$('sort').value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);if(s==='new')a.sort((x,y)=>(y.tag==='New')-(x.tag==='New'));return a}
function render(){let a=list();$('grid').innerHTML=a.map(p=>`<article class="card" onclick="openProduct('${p.id}')"><div class="photo"><span class="tag">${p.tag}</span><button class="wish" onclick="event.stopPropagation();toggleWish('${p.id}')">${wishlist.includes(p.id)?'♥':'♡'}</button><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="info"><h3>${p.name}</h3><div class="meta">${p.category} · <span class="price">${money(p.price)}</span> <span class="old">${money(p.oldPrice)}</span></div></div></article>`).join('');$('empty').classList.toggle('hidden',a.length>0)}
function filterCategory(c){cat=c;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.cat===c));render();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}
function showNew(){cat='All';query='';$('search').value='';render();document.querySelector('#shop').scrollIntoView({behavior:'smooth'});}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();render()}
function openProduct(id){selected=products.find(p=>p.id===id);size=selected.sizes.includes('M')?'M':selected.sizes[0];color=selected.colors[0];renderModal()}
function renderModal(){let p=selected;$('modalBody').innerHTML=`<div class="detail"><img src="${p.image}" alt="${p.name}"><div><span class="eyebrow">${p.category} / ${p.tag}</span><h2>${p.name}</h2><div class="price">${money(p.price)} <span class="old">${money(p.oldPrice)}</span></div><p class="meta">Premium everyday fit with a clean finish. Comfortable, versatile and easy to style.</p><h4>Size</h4><div class="options">${p.sizes.map(x=>`<button class="${x===size?'selected':''}" onclick="size='${x}';renderModal()">${x}</button>`).join('')}</div><h4>Colour</h4><div class="options">${p.colors.map(x=>`<button class="${x===color?'selected':''}" onclick="color='${x}';renderModal()">${x}</button>`).join('')}</div><button class="btn dark" onclick="addProduct('${p.id}')">Add to Bag · ${money(p.price)}</button></div></div>`;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function addProduct(id){let p=products.find(x=>x.id===id),key=`${id}|${size}|${color}`,f=cart.find(x=>x.key===key);if(f)f.qty++;else cart.push({key,id,name:p.name,price:p.price,image:p.image,size,color,qty:1});save();closeModal();openCart()}
function changeQty(key,d){let x=cart.find(i=>i.key===key);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.key!==key);save();renderDrawer()}
function openCart(){openDrawer('Your Bag')}
function openDrawer(title){$('drawerTitle').textContent=title;$('overlay').classList.remove('hidden');$('drawer').classList.add('open');renderDrawer()}
function closeDrawer(){$('overlay').classList.add('hidden');$('drawer').classList.remove('open')}
function renderDrawer(){if(!cart.length){$('drawerBody').innerHTML='<div class="empty">Your bag is waiting for something special.</div>';return}let total=cart.reduce((s,x)=>s+x.price*x.qty,0);$('drawerBody').innerHTML=cart.map(x=>`<div class="cart-item"><img src="${x.image}"><div><h4>${x.name}</h4><div class="meta">Size ${x.size} · ${x.color}</div><div class="price">${money(x.price)}</div><div class="qty"><button onclick="changeQty('${x.key}',-1)">−</button>${x.qty}<button onclick="changeQty('${x.key}',1)">+</button></div></div><button onclick="changeQty('${x.key}',-999)">×</button></div>`).join('')+`<div class="total"><span>Total</span><span>${money(total)}</span></div><button class="btn dark" style="width:100%" onclick="checkout()">Secure Checkout →</button>`}
function checkout(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0);$('drawerTitle').textContent='Checkout';$('drawerBody').innerHTML=`<div class="checkout"><p class="meta">Order total: <b>${money(total)}</b></p><form onsubmit="placeOrder(event)"><input id="name" required placeholder="Full name"><input id="mobile" required pattern="[0-9]{10}" maxlength="10" placeholder="10-digit mobile"><textarea id="address" required rows="3" placeholder="Delivery address"></textarea><div class="checkout-grid"><input id="city" required placeholder="City"><input id="pin" required pattern="[0-9]{6}" maxlength="6" placeholder="Pincode"></div><input id="email" type="email" placeholder="Email (optional)"><select id="payment"><option value="COD">Cash on Delivery</option><option value="UPI">UPI</option></select><button class="btn dark" style="width:100%">Place Order · ${money(total)}</button></form></div>`}
async function placeOrder(e){e.preventDefault();let b=e.target.querySelector('button');b.disabled=true;b.textContent='Placing Order...';let body={customer_name:$('name').value.trim(),mobile:$('mobile').value.trim(),address:$('address').value.trim(),city:$('city').value.trim(),pincode:$('pin').value.trim(),payment_method:$('payment').value,items:cart.map(x=>({product_id:x.id,name:x.name,price:x.price,size:x.size,color:x.color,qty:x.qty,image:x.image}))};try{let r=await fetch(API_BASE+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'Order failed');let id=d.order_id||d.data?.order_id;cart=[];save();$('drawerBody').innerHTML=`<div class="empty"><h3>Order placed ✓</h3><p>Your order ID: <b>${id}</b></p><button class="btn dark" onclick="closeDrawer();trackOrder('${id}')">Track Order</button></div>`}catch(err){alert('Order place nahi ho saka: '+err.message);b.disabled=false;b.textContent='Place Order'}}
async function trackOrder(id){$('trackId').value=id;$('trackResult').innerHTML='<p>Checking...</p>';try{let r=await fetch(API_BASE+'/api/orders/'+encodeURIComponent(id)),d=await r.json();if(!r.ok)throw Error();let o=d.order||d,states=['placed','confirmed','packed','shipped','delivered'],cur=states.indexOf(String(o.status||'placed').toLowerCase());$('trackResult').innerHTML=`<div class="track-card"><b>${o.order_id}</b><p><span class="pill">${String(o.status).toUpperCase()}</span></p><div class="timeline">${states.map((s,i)=>`<div class="step ${i<=cur?'done':''}">${s[0].toUpperCase()+s.slice(1)}</div>`).join('')}</div></div>`}catch(e){$('trackResult').innerHTML='<div class="track-card">Order not found. Please check the ID.</div>'}}
$('search').addEventListener('input',e=>{query=e.target.value;render()});$('sort').addEventListener('change',render);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>filterCategory(b.dataset.cat));$('cartBtn').onclick=openCart;$('overlay').onclick=closeDrawer;$('searchBtn').onclick=()=>{document.querySelector('#shop').scrollIntoView({behavior:'smooth'});$('search').focus()};$('wishBtn').onclick=()=>{openDrawer('Wishlist');$('drawerBody').innerHTML=wishlist.length?wishlist.map(id=>{let p=products.find(x=>x.id===id);return `<div class="cart-item"><img src="${p.image}"><div><h4>${p.name}</h4><div class="price">${money(p.price)}</div></div></div>`}).join(''):'<div class="empty">No saved favourites yet.</div>'};$('trackForm').onsubmit=e=>{e.preventDefault();trackOrder($('trackId').value.trim())};counts();render();
