import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import {createClient} from '@supabase/supabase-js';
dotenv.config();
const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
const PORT=process.env.PORT||10000;
const supabase=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
app.get('/',(_,res)=>res.json({ok:true,service:'Anmol Fashion API'}));
function clean(v){return typeof v==='string'?v.trim():v}
function validate(b){for(const k of ['customer_name','mobile','address','city','pincode','items'])if(b[k]===undefined||b[k]===null||b[k]==='')return `Missing ${k}`;if(!/^\d{10}$/.test(String(b.mobile)))return 'Mobile must be 10 digits';if(!/^\d{6}$/.test(String(b.pincode)))return 'Pincode must be 6 digits';if(!Array.isArray(b.items)||!b.items.length)return 'Cart is empty';return null}
app.post('/api/orders',async(req,res)=>{try{const b=req.body||{},v=validate(b);if(v)return res.status(400).json({error:v});const order_id='AF'+Date.now().toString().slice(-8);const items=b.items.map(x=>({product_id:clean(x.product_id)||null,name:clean(x.name),price:Number(x.price)||0,size:clean(x.size)||null,color:clean(x.color)||null,qty:Math.max(1,Number(x.qty)||1),image:clean(x.image)||null}));const total_amount=items.reduce((s,x)=>s+x.price*x.qty,0);const row={order_id,customer_name:clean(b.customer_name),mobile:clean(b.mobile),address:clean(b.address),city:clean(b.city),pincode:clean(b.pincode),payment_method:clean(b.payment_method)||'COD',items,total_amount,status:'placed'};const {data,error}=await supabase.from('orders').insert(row).select('*').single();if(error){console.error(error);return res.status(500).json({error:error.message})}res.status(201).json({ok:true,order_id,data})}catch(e){console.error(e);res.status(500).json({error:'Internal server error'})}});
app.get('/api/orders/:orderId',async(req,res)=>{try{const {data,error}=await supabase.from('orders').select('order_id,customer_name,status,total_amount,payment_method,created_at,items').eq('order_id',req.params.orderId).maybeSingle();if(error)return res.status(500).json({error:error.message});if(!data)return res.status(404).json({error:'Order not found'});res.json({ok:true,order:data})}catch(e){res.status(500).json({error:'Internal server error'})}});
app.get('/api/admin/orders',async(req,res)=>{if(process.env.ADMIN_KEY&&req.header('x-admin-key')!==process.env.ADMIN_KEY)return res.status(401).json({error:'Unauthorized'});const {data,error}=await supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(Math.min(Number(req.query.limit)||100,500));if(error)return res.status(500).json({error:error.message});res.json({ok:true,orders:data||[]})});
app.patch('/api/admin/orders/:orderId/status',async(req,res)=>{if(process.env.ADMIN_KEY&&req.header('x-admin-key')!==process.env.ADMIN_KEY)return res.status(401).json({error:'Unauthorized'});const allowed=['placed','confirmed','packed','shipped','delivered','cancelled'],status=String(req.body?.status||'').toLowerCase();if(!allowed.includes(status))return res.status(400).json({error:'Invalid status'});const {data,error}=await supabase.from('orders').update({status}).eq('order_id',req.params.orderId).select('*').single();if(error)return res.status(500).json({error:error.message});res.json({ok:true,order:data})});
app.listen(PORT,()=>console.log(`Anmol Fashion API running on ${PORT}`));
